DROP TABLE IF EXISTS todos;

CREATE TABLE IF NOT EXISTS todos(
	id INT PRIMARY KEY AUTO_INCREMENT,
	todo VARCHAR(255) NOT NULL,
	detail text,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);